<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-DCH1U2PQ" failures="2" tests="2" name="Error Validation Test" time="19.8" errors="0" timestamp="2024-09-25T16:08:59 IST">
  <testcase classname="com.nithin.tests.ErrorValidationTest" name="LoginErrorValidation" time="0.311">
    <failure type="java.lang.AssertionError" message="expected [div] but found [Incorrect emaile or password.]">
      <![CDATA[java.lang.AssertionError: expected [div] but found [Incorrect emaile or password.]
at com.nithin.tests.ErrorValidationTest.LoginErrorValidation(ErrorValidationTest.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="com.nithin.tests.ErrorValidationTest" name="productErrorValidation" time="12.628">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nithin.tests.ErrorValidationTest.productErrorValidation(ErrorValidationTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- productErrorValidation -->
</testsuite> <!-- Error Validation Test -->
